id: AFD30CE49
base_file: f64E1.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:08:50.331112
  last_modified_at: 2022-06-17 14:08:50.331124
