id: AFD30CE49
base_file: f3394.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:08:50.326426
  last_modified_at: 2022-06-17 14:08:50.326438
