id: AFD30CE49
base_file: f318E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:08:50.320416
  last_modified_at: 2022-06-17 14:08:50.320424
