id: AFD30CE49
base_file: f2514.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:08:50.316363
  last_modified_at: 2022-06-17 14:08:50.316380
