id: AFD30CE49
base_file: fCE04.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:08:50.335355
  last_modified_at: 2022-06-17 14:08:50.335361
